// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"haohuynh123-cola/ecommce/internal/modules/auth"
	"haohuynh123-cola/ecommce/internal/modules/cart"
	"haohuynh123-cola/ecommce/internal/modules/comment"
	"haohuynh123-cola/ecommce/internal/modules/order"
	"haohuynh123-cola/ecommce/internal/modules/product"
	"haohuynh123-cola/ecommce/internal/platform/config"
	"time"

	"github.com/jmoiron/sqlx"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitializeAuthHandler(db *sqlx.DB, rdb *redis.Client, cacheTTL time.Duration, jwtCfg config.JWTConfig, smtpCfg config.SMTPConfig, oauthCfg config.OAuthConfig) *auth.AuthHandler {
	iUserRepository := auth.NewUserRepository(db)
	string2 := auth.ProvideJWTSecret(jwtCfg)
	userCache := auth.NewUserCache(rdb, cacheTTL)
	iAuthService := auth.NewAuthService(iUserRepository, string2, userCache, smtpCfg, oauthCfg)
	authHandler := auth.NewAuthHandler(iAuthService, jwtCfg)
	return authHandler
}

func InitializeProductHandler(db *sqlx.DB, rdb *redis.Client, cacheTTL time.Duration) *product.ProductHandler {
	productRepository := product.NewProductRepository(db)
	productCache := product.NewProductCache(rdb, cacheTTL)
	productService := product.NewProductService(productRepository, productCache)
	productHandler := product.NewProductHandler(productService)
	return productHandler
}

func InitializeCartHandler(db *sqlx.DB, rdb *redis.Client, cacheTTL time.Duration, jwtCfg config.JWTConfig) *cart.CartHandler {
	cartRepository := cart.NewCartRepository(db)
	cartCache := cart.NewCartCache(rdb, cacheTTL)
	cartService := cart.NewCartService(cartRepository, cartCache)
	cartHandler := cart.NewCartHandler(cartService, jwtCfg)
	return cartHandler
}

func InitializeOrderHandler(db *sqlx.DB, rdb *redis.Client, cacheTTL time.Duration, jwtCfg config.JWTConfig) *order.OrderHandler {
	orderRepository := order.NewOrderRepository(db)
	orderItemRepository := order.NewOrderItemRepository(db)
	productRepository := product.NewProductRepository(db)
	orderActivityRepository := order.NewOrderActivityRepository(db)
	orderCache := order.NewOrderCache(rdb, cacheTTL)
	orderService := order.NewOrderService(orderRepository, orderItemRepository, productRepository, orderActivityRepository, orderCache)
	orderHandler := order.NewOrderHandler(orderService, jwtCfg)
	return orderHandler
}

func InitializeCommentHandler(db *sqlx.DB, rdb *redis.Client, cacheTTL time.Duration, jwtCfg config.JWTConfig) *comment.CommentHandler {
	commentRepository := comment.NewCommentRepository(db)
	commentService := comment.NewCommentService(commentRepository)
	commentHandler := comment.NewCommentHandler(commentService)
	return commentHandler
}
