// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"haohuynh123-cola/ecommce/internal/cache"
	"haohuynh123-cola/ecommce/internal/config"
	"haohuynh123-cola/ecommce/internal/handler"
	"haohuynh123-cola/ecommce/internal/repo"
	"haohuynh123-cola/ecommce/internal/service"
	"time"

	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitializeAuthHandler(db *sqlx.DB, jwtCfg config.JWTConfig) *handler.AuthHandler {
	iUserRepository := repo.NewUserRepository(db)
	string2 := provideJWTSecret(jwtCfg)
	iAuthService := service.NewAuthService(iUserRepository, string2)
	authHandler := handler.NewAuthHandler(iAuthService, jwtCfg)
	return authHandler
}

func InitializeProductHandler(db *sqlx.DB, rdb *redis.Client, cacheTTL time.Duration) *handler.ProductHandler {
	productRepository := repo.NewProductRepository(db)
	productCache := cache.NewProductCache(rdb, cacheTTL)
	productService := service.NewProductService(productRepository, productCache)
	productHandler := handler.NewProductHandler(productService)
	return productHandler
}

func InitializeCartHandler(db *sqlx.DB, rdb *redis.Client, cacheTTL time.Duration, jwtCfg config.JWTConfig) *handler.CartHandler {
	cartRepository := repo.NewCartRepository(db)
	cartCache := cache.NewCartCache(rdb, cacheTTL)
	cartService := service.NewCartService(cartRepository, cartCache)
	cartHandler := handler.NewCartHandler(cartService, jwtCfg)
	return cartHandler
}

func InitializeOrderHandler(db *sqlx.DB, rdb *redis.Client, cacheTTL time.Duration, jwtCfg config.JWTConfig) *handler.OrderHandler {
	orderRepository := repo.NewOrderRepository(db)
	orderItemRepository := repo.NewOrderItemRepository(db)
	productRepository := repo.NewProductRepository(db)
	orderActivityRepository := repo.NewOrderActivityRepository(db)
	orderCache := cache.NewOrderCache(rdb, cacheTTL)
	orderService := service.NewOrderService(orderRepository, orderItemRepository, productRepository, orderActivityRepository, orderCache)
	orderHandler := handler.NewOrderHandler(orderService, jwtCfg)
	return orderHandler
}

// wire.go:

func provideJWTSecret(cfg config.JWTConfig) string {
	return cfg.SecretKey
}

var AuthSet = wire.NewSet(repo.NewUserRepository, provideJWTSecret, service.NewAuthService, handler.NewAuthHandler)

var ProductSet = wire.NewSet(repo.NewProductRepository, cache.NewProductCache, service.NewProductService, handler.NewProductHandler)

var CartSet = wire.NewSet(repo.NewCartRepository, cache.NewCartCache, service.NewCartService, handler.NewCartHandler)

var OrderSet = wire.NewSet(repo.NewOrderRepository, repo.NewOrderItemRepository, repo.NewProductRepository, repo.NewOrderActivityRepository, cache.NewOrderCache, service.NewOrderService, handler.NewOrderHandler)
