@SERVER=http://localhost:8080/api/v1
//Token triggered after login, copy and paste here for testing protected routes
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzczNDUyODIsImdtYWlsIjoiaHV5bmhraW5oYW9AZ21pYWwuY29tIiwibmFtZSI6Ikh14buzbmggS8OtbiBIw6BvIiwidXNlcl9pZCI6MX0.31CRNGQe5l1Gi4Bd5xJOo9_Z0AK6dAvPrtXW_mEykq0
# Test user registration
POST {{SERVER}}/auth/register
Content-Type: application/json

{
  "name": "Huỳnh Kín Hào",
  "email": "huynhkinhao1910@gmail.com",
  "password": "123456333"
}

###
# Test user login
POST {{SERVER}}/auth/login
Content-Type: application/json

{
  "email": "huynhkinhao1910@gmail.com",
  "password": "123456"
}
###
# Test user logout
GET {{SERVER}}/auth/me
Content-Type: application/json
Authorization: {{token}}

