server:
      port: 8080
      host: localhost
      debug: true

database:
      host: localhost
      port: 3306
      user: sunny
      password: "123456"
      database_name: ecommerce
redis:
      host: localhost
      port: 6379
      password: ""
      db: 0

jwt:
      secret_key: "haohuynh19123131312312312"

log:
      level: "info"
      file_path: "logs/app.log"

smtp:
      host: "smtp.example.com"
      port: 587
      username: "your_username"
      password: "your_password"

oauth:
      google:
            client_id: "<your-google-oauth-client-id>.apps.googleusercontent.com"
