server:
      port: 8080
      host: localhost

database:
      host: localhost
      port: 3306
      user: sunny
      password: "123456"
      database_name: ecommerce

jtw:
      secret_key: "haohuynh19123131312312312"